USE [master]
GO

/****** Object:  Database [BigSchool]    Script Date: 14/07/2021 22:28:13 ******/
CREATE DATABASE [BigSchool]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BigSchool', FILENAME = N'D:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\BigSchool.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BigSchool_log', FILENAME = N'D:\SQL\MSSQL15.MSSQLSERVER\MSSQL\DATA\BigSchool_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BigSchool].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BigSchool] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BigSchool] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BigSchool] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BigSchool] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BigSchool] SET ARITHABORT OFF 
GO

ALTER DATABASE [BigSchool] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BigSchool] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BigSchool] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BigSchool] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BigSchool] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BigSchool] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BigSchool] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BigSchool] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BigSchool] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BigSchool] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BigSchool] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BigSchool] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BigSchool] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BigSchool] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BigSchool] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BigSchool] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BigSchool] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BigSchool] SET RECOVERY FULL 
GO

ALTER DATABASE [BigSchool] SET  MULTI_USER 
GO

ALTER DATABASE [BigSchool] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BigSchool] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BigSchool] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BigSchool] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BigSchool] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BigSchool] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [BigSchool] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BigSchool] SET  READ_WRITE 
GO


